#!/usr/bin/env python3
import base64, pathlib, struct, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ref" / "tinygrad"))

from tinygrad.device import Device
from tinygrad.runtime.support.hcq import HWQueue


KERNEL_CUBIN = base64.b64decode(
  "f0VMRgIBATMHAAAAAAAAAAIAvgCAAAAAAAAAAAAAAACACgAAAAAAAIAHAAAAAAAAVgVWAEAAOAADAEAADAABAAAu"
  "c2hzdHJ0YWIALnN0cnRhYgAuc3ltdGFiAC5zeW10YWJfc2huZHgALm52LmluZm8ALnRleHQuRV80AC5udi5pbmZv"
  "LkVfNAAubnYuc2hhcmVkLkVfNAAubnYuY29uc3RhbnQwLkVfNAAucmVsLm52LmNvbnN0YW50MC5FXzQALmRlYnVn"
  "X2ZyYW1lAC5yZWwuZGVidWdfZnJhbWUALnJlbGEuZGVidWdfZnJhbWUALm52LmNhbGxncmFwaAAubnYucHJvdG90"
  "eXBlAC5udi5yZWwuYWN0aW9uAAAuc2hzdHJ0YWIALnN0cnRhYgAuc3ltdGFiAC5zeW10YWJfc2huZHgALm52Lmlu"
  "Zm8ALnRleHQuRV80AC5udi5pbmZvLkVfNAAubnYuc2hhcmVkLkVfNAAucmVsLm52LmNvbnN0YW50MC5FXzQALm52"
  "LmNvbnN0YW50MC5FXzQALmRlYnVnX2ZyYW1lAC5yZWwuZGVidWdfZnJhbWUALnJlbGEuZGVidWdfZnJhbWUALm52"
  "LmNhbGxncmFwaAAubnYucHJvdG90eXBlAC5udi5yZWwuYWN0aW9uAEVfNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAyAAAAAwALAAAAAAAAAAAAAAAAAAAAAABuAAAAAwAKAAAAAAAAAAAAAAAAAAAAAACAAAAAAwAEAAAA"
  "AAAAAAAAAAAAAAAAAACwAAAAAwAHAAAAAAAAAAAAAAAAAAAAAADMAAAAAwAIAAAAAAAAAAAAAAAAAAAAAADbAAAA"
  "EhALAAAAAAAAAAAAAAIAAAAAAAD/////JAAAAAAAAAD//////////wMABHz/////DwyBgIAoAAj/gYAoCIGAgCgA"
  "AAD/////NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAEBAAAAAQ8AAAADIGAgCgABPz//z8AAAAAAAAA"
  "BC8IAAYAAAAOAAAABBEIAAYAAAAAAAAABBIIAAYAAAAAAAAABDcEAIAAAAABNQAABAoIAAIAAABgARgAAxkYAAQX"
  "DAAAAAAAAgAQAADwIQAEFwwAAAAAAAEACAAA8CEABBcMAAAAAAAAAAAAAPAhAAMb/wAEHAQA8AAAAAQFDAABAAAA"
  "AQAAAAEAAAAAAAAA/////wAAAAD+////AAAAAP3///8AAAAA/P///wAAAABzAAAAAAAAAAAAABElAAU2RAAAAAAA"
  "AAACAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ6AQAACgAAAA8AAADkDwACegQAAFwAAAAPAAAA4g8AuXoEAABGAAAACgAA"
  "AOIPAAJ6BQAAXQAAAA8AAADkDwACegIAAFoAAAAPAAAA5A8AAnoDAABbAAAADwAAAOQPAIF5BAQEAAAAAB0eDACo"
  "DgCBeQgCBAAAAAAdHgwApA4AIHILCwcAAAAAAEAAAOJPACByCgoGAAAAAABAAADiDwAgcgkJBQAAAAAAQAAA4g8A"
  "IHIICAQAAAAAAEAAAOIPAAJ6BgAAWAAAAA8AAADEDwACegcAAFkAAAAPAAAAyg8AhnkABggAAAAEHRAMAOIPAE15"
  "AAAAAAAAAACAAwDqDwBHeQAA8P//////gwMAwA8AGHkAAAAAAAAAAAAAAMAPABh5AAAAAAAAAAAAAADADwAYeQAA"
  "AAAAAAAAAAAAwA8AGHkAAAAAAAAAAAAAAMAPABh5AAAAAAAAAAAAAADADwAYeQAAAAAAAAAAAAAAwA8AGHkAAAAA"
  "AAAAAAAAAMAPABh5AAAAAAAAAAAAAADADwAYeQAAAAAAAAAAAAAAwA8AGHkAAAAAAAAAAAAAAMAPABh5AAAAAAAA"
  "AAAAAADADwAYeQAAAAAAAAAAAAAAwA8AGHkAAAAAAAAAAAAAAMAPABh5AAAAAAAAAAAAAADADwAYeQAAAAAAAAAA"
  "AAAAwA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAA2wAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA"
  "AAALAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAbAQAAAAAAAN8AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"
  "EwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAACoAAAAAAAAAAIAAAAGAAAACAAAAAAAAAAYAAAAAAAAAIAA"
  "AAABAAAAAAAAAAAAAAAAAAAAAAAAAKgCAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAApAAAA"
  "AAAAcAAAAAAAAAAAAAAAAAAAAAAYAwAAAAAAACQAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAPAAAAAAA"
  "AHBAAAAAAAAAAAAAAAAAAAAAPAMAAAAAAABoAAAAAAAAAAMAAAALAAAABAAAAAAAAAAAAAAAAAAAALAAAAABAABw"
  "AAAAAAAAAAAAAAAAAAAAAKQDAAAAAAAAIAAAAAAAAAADAAAAAAAAAAQAAAAAAAAACAAAAAAAAADMAAAACwAAcAAA"
  "AAAAAAAAAAAAAAAAAADIAwAAAAAAABAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAjQAAAAkAAABAAAAA"
  "AAAAAAAAAAAAAAAA2AMAAAAAAAAQAAAAAAAAAAMAAAAEAAAACAAAAAAAAAAQAAAAAAAAAFgAAAABAAAAQgAAAAAA"
  "AAAAAAAAAAAAAOgDAAAAAAAAeAEAAAAAAAAAAAAACwAAAAQAAAAAAAAAAAAAAAAAAAAyAAAAAQAAAAYAAAAAAAAA"
  "AAAAAAAAAACABQAAAAAAAAACAAAAAAAAAwAAAAYAAA6AAAAAAAAAAAAAAAAAAAAABgAAAAUAAACACgAAAAAAAAAA"
  "AAAAAAAAAAAAAAAAAACoAAAAAAAAAKgAAAAAAAAACAAAAAAAAAABAAAABQAAAOgDAAAAAAAAAAAAAAAAAAAAAAAA"
  "AAAAAJgDAAAAAAAAmAMAAAAAAAAIAAAAAAAAAAEAAAAFAAAAgAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAAAAAAA"
  "AACoAAAAAAAAAAgAAAAAAAAA"
)


def trace_submits():
  real_submit = HWQueue.submit
  count = 0
  def traced_submit(self, dev, var_vals=None):
    nonlocal count
    if var_vals is not None: self._apply_var_vals(var_vals)
    count += 1
    words = [int(word) for word in self._q]
    print(f"submit #{count}: {type(self).__name__} words={len(words)}")
    print("  words_hex=" + " ".join(f"{word:08x}" for word in words))
    return real_submit(self, dev, None)
  HWQueue.submit = traced_submit
  return real_submit


def main():
  dev = Device["NV"]
  print(f"device={dev.device} iface={type(dev.iface).__name__}")
  a = dev.allocator.alloc(16)
  b = dev.allocator.alloc(16)
  out = dev.allocator.alloc(16)
  dev.allocator._copyin(a, memoryview(struct.pack("4f", 1.0, 2.0, 3.0, 4.0)))
  dev.allocator._copyin(b, memoryview(struct.pack("4f", 10.0, 20.0, 30.0, 40.0)))
  dev.allocator._copyin(out, memoryview(bytes(16)))
  program = dev.runtime("E_4", KERNEL_CUBIN)
  real_submit = trace_submits()
  try:
    program(out, a, b, global_size=(1, 1, 1), local_size=(1, 1, 1), wait=True)
  finally:
    HWQueue.submit = real_submit
  result_bytes = bytearray(16)
  dev.allocator._copyout(memoryview(result_bytes), out)
  print(f"result={list(struct.unpack('4f', result_bytes))}")
  print("submitted embedded NV mul kernel")


if __name__ == "__main__":
  main()
